In [3]:
import torch

x = torch.tensor([[1.0, 2.0, 3.0],[4.0, 5.0, 6.0]], requires_grad=True)
print(x)

tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [4]:
y = x + 2
print(y)

tensor([[3., 4., 5.],
        [6., 7., 8.]], grad_fn=<AddBackward0>)


In [6]:
y.sum().backward()
print(x.grad)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
