In [1]:
import torch
version = torch.__version__
print(f"PyTorch version: {version}")

PyTorch version: 2.10.0+cu128


In [2]:
if torch.cuda.is_available():
    print("CUDA is available. You can use GPU acceleration.")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available. Using CPU.")

CUDA is available. You can use GPU acceleration.
Using GPU: Tesla T4


# Creating a Tensor


In [4]:
a = torch.empty(2,3)
print(a)

tensor([[9.9573e-09, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])


In [5]:
type(a)

torch.Tensor

In [6]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(2,3)

tensor([[0.6416, 0.6098, 0.5435],
        [0.2010, 0.3618, 0.2270]])

In [11]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

# Tensor Shapes

In [14]:
x = torch.tensor([1,2,3])
print(x)

tensor([1, 2, 3])


In [15]:
x.shape

torch.Size([3])

# Tensor Data Type

In [16]:
x.dtype

torch.int64

In [17]:
torch.tensor([1,2,3], dtype=torch.float32)

tensor([1., 2., 3.])

In [18]:
x.to(torch.float32)

tensor([1., 2., 3.])

In [19]:
a = torch.rand(2,3)
b = torch.rand(2,3)


In [20]:
a + b

tensor([[1.1260, 1.3614, 1.6819],
        [0.5626, 1.8200, 1.1675]])

In [21]:
a - b

tensor([[-0.6128,  0.2259,  0.1997],
        [-0.2962,  0.0492,  0.0197]])

In [22]:
a * b


tensor([[0.2231, 0.4506, 0.6972],
        [0.0572, 0.8275, 0.3407]])